<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marika M. Cusick">
<meta name="author" content="Fernando Alarid-Escudero">
<meta name="author" content="Jeremy D. Goldhaber-Fiebert">
<meta name="author" content="Sherri Rose">
<meta name="dcterms.date" content="2025-02-21">

<title>A novel decision modeling framework for health policy analyses when outcomes are influenced by social and disease processes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="manuscript_draft_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript_draft_files/libs/quarto-html/quarto.js"></script>
<script src="manuscript_draft_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript_draft_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="manuscript_draft_files/libs/quarto-html/anchor.min.js"></script>
<link href="manuscript_draft_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript_draft_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript_draft_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript_draft_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript_draft_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A novel decision modeling framework for health policy analyses when outcomes are influenced by social and disease processes</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Marika M. Cusick <a href="mailto:mmcusick@stanford.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Health Policy, Stanford University School of Medicine
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Fernando Alarid-Escudero </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Health Policy, Stanford University School of Medicine
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Jeremy D. Goldhaber-Fiebert </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Health Policy, Stanford University School of Medicine
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Sherri Rose </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Health Policy, Stanford University School of Medicine
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 21, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="abstract" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="abstract">Abstract</h2>
<p><strong>Purpose:</strong>&nbsp;Health policy simulation models incorporate disease processes but often ignore social processes that influence health outcomes, potentially leading to suboptimal policy recommendations. To address this gap, we developed a novel decision-analytic modeling framework to integrate social processes.</p>
<p><strong>Methods or Design:</strong>&nbsp;We evaluated a simplified decision problem using two models: a standard decision-analytic model and a model incorporating our social factors framework. The standard model simulated individuals transitioning through three disease natural history states–healthy, sick, and dead–without accounting for differential health system utilization. Our social factors framework incorporated heterogeneous health insurance coverage, which influenced disease progression and health system utilization. We assessed the impact of a new treatment on a cohort of 100,000 healthy, non-Hispanic Black and non-Hispanic white 40-year-old adults. Main outcomes included life expectancy, cumulative incidence and duration of sickness, and health system utilization over the lifetime. Secondary outcomes included costs, quality-adjusted life years, and incremental cost-effectiveness ratios.</p>
<p><strong>Results:</strong> In the standard model, the new treatment increased life expectancy by 2.7 years for both non-Hispanic Black and non-Hispanic white adults, without affecting racial/ethnic gaps in life expectancy. However, incorporating known racial/ethnic disparities in health insurance coverage with the social factors framework led to smaller life expectancy gains for non-Hispanic Black adults (2.0 years) compared to non-Hispanic white adults (2.2 years), increasing racial/ethnic disparities in life expectancy.</p>
<p><strong>Limitations:</strong>&nbsp;The availability of social factors and complexity of causal pathways between factors may pose challenges in applying our social factors framework.</p>
<p><strong>Conclusions:</strong>&nbsp;Excluding social processes from health policy modeling can result in unrealistic projections and biased policy recommendations. Incorporating a social factors framework enhances simulation models’ effectiveness in evaluating interventions with health equity implications.</p>
</section>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>Healthcare policymakers face challenging decisions regarding allocating resources to new or existing interventions subject to constrained budgets. Simulation models can offer rigorous evidence on the long-term health and cost implications of these decisions for populations.<span class="citation" data-cites="sanders2016recommendations"><sup><a href="#ref-sanders2016recommendations" role="doc-biblioref">1</a></sup></span> Increasingly, policymakers are concerned about how healthcare technologies impact health disparities, which can be examined by assessing the distribution of health outcomes and costs across a population.<span class="citation" data-cites="10.1093/acprof:oso/9780190492939.001.0001"><sup><a href="#ref-10.1093/acprof:oso/9780190492939.001.0001" role="doc-biblioref">2</a></sup></span> However, existing methods may not be sufficient to provide rigorous quantitative evidence on the implications of health disparities.</p>
<p>Health policy simulation modeling typically focuses on disease natural history to guide policy decisions. However, these models rarely explicitly incorporate the impact of social factors on health outcomes, including patient healthcare access, health-seeking behavior, socioeconomic status, and other structural barriers. Prior research suggests that up to 40% of explainable variation in health outcomes can be attributed to social and economic factors.<span class="citation" data-cites="hood2016county"><sup><a href="#ref-hood2016county" role="doc-biblioref">3</a></sup></span> Considering and incorporating these factors into health policy simulation models could be critical for informed decision-making.</p>
<p>In this paper, we propose a framework for integrating social factors into health policy decision-analytic models, henceforth referred to as the social factors framework. To demonstrate the value of our framework, we compared model results from a standard model and a model incorporating the social factors framework for a simplified decision problem.</p>
</section>
<section id="methods" class="level2 page-columns page-full" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="methods"><span class="header-section-number">2</span> Methods</h2>
<section id="social-factors-framework" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="social-factors-framework"><span class="header-section-number">2.1</span> Social factors framework</h3>
<p>Our social factors framework includes three components: disease natural history, health system utilization, and social factors (<a href="#fig-figure1" class="quarto-xref">Figure&nbsp;1</a>). In disease natural history, individuals transition through health states specific to a given disease. In the health system utilization component, individuals transition between various levels of healthcare engagement, such as having no regular healthcare access, receiving regular care, being diagnosed, receiving treatment, and discontinuing treatment. An individual’s disease state can impact their health system utilization. For example, individuals in more advanced disease stages may be more likely to be diagnosed or receive treatment. Additionally, health system utilization can impact disease progression. This can occur when, for instance, individuals receiving treatment may experience slowed disease progression or reduced mortality risk. The third component, social factors, includes health insurance status, socioeconomic status, and additional structural barriers, which may impact both disease natural history and health system utilization.</p>
<div id="fig-figure1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-figure1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/proposedframework.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figure1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: General social factors framework for including social processes in health policy decision-analytic models
</figcaption>
</figure>
</div>
</section>
<section id="simplified-decision-problem" class="level3 page-columns page-full" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="simplified-decision-problem"><span class="header-section-number">2.2</span> Simplified decision problem</h3>
<p>We compared model results for a simplified decision problem using two state-transition decision-analytic microsimulation models: 1) a standard model; and 2) a model incorporating our social factors framework (<a href="#fig-figure2" class="quarto-xref">Figure&nbsp;2</a>). We selected a microsimulation model, an individual-based state-transition model, for analysis as it allows for differentiated simulation pathways according to individual characteristics.<span class="citation" data-cites="krijkamp2018microsimulation"><sup><a href="#ref-krijkamp2018microsimulation" role="doc-biblioref">4</a></sup></span></p>
<p>In the standard model, each individual had two characteristics (age and race/ethnicity). As individuals aged, they transitioned through three disease natural history states: healthy, sick, and dead. The standard model incorporated racial and ethnic differences in mortality according to age-sex-race-ethnicity-specific U.S. life table rates.<span class="citation" data-cites="arias2023united"><sup><a href="#ref-arias2023united" role="doc-biblioref">5</a></sup></span> We assumed all individuals were in the health system with regular healthcare access, and sick individuals could be detected and treated for disease and subsequently discontinue treatment.</p>
<p>To incorporate the social factors framework, we modified the standard model by adding a social factor, health insurance status. Based on evidence from prior studies, we assumed health insurance status impacted baseline mortality rates and access to regular healthcare.<span class="citation" data-cites="wilper2009health hill2024health fernandez2019medication tolbert2024uninsured"><sup><a href="#ref-wilper2009health" role="doc-biblioref">6</a>–<a href="#ref-tolbert2024uninsured" role="doc-biblioref">9</a></sup></span> We adjusted age-sex-race-ethnicity-specific U.S. life table mortality rates by insurance status assuming a constant race/ethnicity-specific prevalence of uninsured individuals and a hazard ratio for increased mortality risk among those uninsured.<span class="citation" data-cites="wilper2009health hill2024health"><sup><a href="#ref-wilper2009health" role="doc-biblioref">6</a>,<a href="#ref-hill2024health" role="doc-biblioref">7</a></sup></span></p>
<p>Insurance status also impacted access to routine healthcare and adherence to treatment. In the model with the social factors framework, we added a health system utilization state, “not in health system,” which represented individuals without access to routine healthcare. From the outset, uninsured individuals were less likely to be in the health system with routine access to healthcare compared to those with health insurance coverage.<span class="citation" data-cites="fernandez2019medication tolbert2024uninsured"><sup><a href="#ref-fernandez2019medication" role="doc-biblioref">8</a>,<a href="#ref-tolbert2024uninsured" role="doc-biblioref">9</a></sup></span> Details for estimating these probabilities are provided in <a href="#sec-population" class="quarto-xref">Section&nbsp;2.3</a>. Additionally, we assumed that uninsured sick individuals discontinued treatment at faster rates compared to those with insurance. <a href="#fig-figure2" class="quarto-xref">Figure&nbsp;2</a> provides a visual comparison of the two models and the transition probability dependencies.</p>
<div class="page-columns page-full">
<div id="fig-figure2" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-figure2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="figures/simplifiedexample.png" class="img-fluid figure-img column-page" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-figure2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Diagrams and transition dependencies for the standard model and social factors framework in the simplified decision problem
</figcaption>
</figure>
</div>
</div>
</section>
<section id="sec-population" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="sec-population"><span class="header-section-number">2.3</span> Population and intervention</h3>
<p>We simulated a cohort of 100,000 healthy, non-Hispanic Black and non-Hispanic white 40-year-old men and women. We estimated the sex and racial/ethnic group distribution of the simulated cohort using a cohort of survey participants from the U.S. National Health and Nutrition Survey (NHANES) 2013-2018 data.<span class="citation" data-cites="CDC2018"><sup><a href="#ref-CDC2018" role="doc-biblioref">10</a></sup></span> The survey participants were aged between 35 and 45 years, self-identified as either non-Hispanic Black or non-Hispanic white, and self-identified as either female or male.</p>
<p>For our social factors framework, we estimated additional quantities: the proportions of adults with health insurance coverage by race/ethnicity and proportions of adults with routine healthcare access by insurance status. Insurance coverage proportions by race/ethnicity were estimated with the fraction of individuals in each racial/ethnic group who responded “yes” to the NHANES survey question “Are you covered by health insurance or some other kind of healthcare plan?” Given the stylized nature of the model, for simplicity, we assumed insurance status remained constant over the lifetime. Routine healthcare access proportions were estimated using the fraction of individuals with and without health insurance coverage who responded “yes” or “there is more than one place” to the NHANES survey question “Is there a place that you usually go when you are sick or you need advice about your health?”</p>
<p>Our simplified decision problem involved evaluating the impact of adding a hypothetical new treatment to standard of care. Without treatment, the sickness increased an individual’s mortality rate by a factor of 4 (i.e., a hazard ratio of 4). An existing standard of care treatment halved the mortality rate from sickness. The new treatment eliminated all disease-specific excess mortality, such that patients progressed to death at their baseline mortality rates. Base case model parameters are provided in <a href="#tbl-table1" class="quarto-xref">Table&nbsp;1</a>.</p>
<div id="tbl-table1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-table1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Base case model parameters for standard model and social factors framework
</figcaption>
<div aria-describedby="tbl-table1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Parameter</strong></td>
<td></td>
<td><strong>Standard Model</strong></td>
<td style="text-align: left;"><strong>Social Factors Framework</strong></td>
</tr>
<tr class="even">
<td><em>Disease natural history annual transition probabilities</em></td>
<td></td>
<td></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>Healthy<span class="citation" data-cites="arias2023united"><sup><a href="#ref-arias2023united" role="doc-biblioref">5</a></sup></span></td>
<td>Dead</td>
<td>Age-sex-race-ethnicity-specific U.S. life tables</td>
<td style="text-align: left;">Age-sex-race-ethnicity-insurance-specific U.S. life tables</td>
</tr>
<tr class="even">
<td>Healthy</td>
<td>Sick</td>
<td>0.05</td>
<td style="text-align: left;">0.05</td>
</tr>
<tr class="odd">
<td><em>Disease natural history transition hazard ratios</em></td>
<td></td>
<td></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>Sick (not detected/treated)</td>
<td>Dead</td>
<td>4.0</td>
<td style="text-align: left;">4.0</td>
</tr>
<tr class="odd">
<td><em>Health system transition annual probabilities</em></td>
<td></td>
<td></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>Out of health system</td>
<td>In health system</td>
<td>0.05</td>
<td style="text-align: left;">0.05</td>
</tr>
<tr class="odd">
<td>In health system</td>
<td>Detected/treated</td>
<td>0.20</td>
<td style="text-align: left;">0.20</td>
</tr>
<tr class="even">
<td>Detected/treated</td>
<td>Detected/untreated</td>
<td>0.02</td>
<td style="text-align: left;">0.02</td>
</tr>
<tr class="odd">
<td><em>Health system transition hazard ratios (uninsured individuals)</em></td>
<td></td>
<td></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>Out of system</td>
<td>In system</td>
<td></td>
<td style="text-align: left;">0.20</td>
</tr>
<tr class="odd">
<td>In system</td>
<td>Detected/treated</td>
<td></td>
<td style="text-align: left;">0.20</td>
</tr>
<tr class="even">
<td>Detected/treated</td>
<td>Detected/untreated</td>
<td></td>
<td style="text-align: left;">5.0</td>
</tr>
<tr class="odd">
<td><em>Treatment effectiveness hazard ratios on mortality</em></td>
<td></td>
<td></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>Standard of care</td>
<td></td>
<td>0.50</td>
<td style="text-align: left;">0.50</td>
</tr>
<tr class="odd">
<td>Standard of care and new treatment</td>
<td></td>
<td>0.25</td>
<td style="text-align: left;">0.25</td>
</tr>
<tr class="even">
<td><em>Mortality adjustments by insurance status</em></td>
<td></td>
<td></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>Hazard ratio for increased mortality among uninsured adults<span class="citation" data-cites="wilper2009health"><sup><a href="#ref-wilper2009health" role="doc-biblioref">6</a></sup></span></td>
<td></td>
<td></td>
<td style="text-align: left;">1.4</td>
</tr>
<tr class="even">
<td>Prevalence of uninsured across nonelderly population (0-64y)<span class="citation" data-cites="hill2024health"><sup><a href="#ref-hill2024health" role="doc-biblioref">7</a></sup></span></td>
<td>Non-Hispanic Black</td>
<td></td>
<td style="text-align: left;">10%</td>
</tr>
<tr class="odd">
<td></td>
<td>Non-Hispanic white</td>
<td></td>
<td style="text-align: left;">7%</td>
</tr>
<tr class="even">
<td><em>Cohort characteristics</em><span class="citation" data-cites="CDC2018"><sup><a href="#ref-CDC2018" role="doc-biblioref">10</a></sup></span></td>
<td></td>
<td></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td>Sex</td>
<td>Female</td>
<td>52%</td>
<td style="text-align: left;">52%</td>
</tr>
<tr class="even">
<td></td>
<td>Male</td>
<td>48%</td>
<td style="text-align: left;">48%</td>
</tr>
<tr class="odd">
<td>Race/ethnicity</td>
<td>Non-Hispanic Black</td>
<td>18%</td>
<td style="text-align: left;">18%</td>
</tr>
<tr class="even">
<td></td>
<td>Non-Hispanic white</td>
<td>82%</td>
<td style="text-align: left;">82%</td>
</tr>
<tr class="odd">
<td>Insurance coverage</td>
<td>Non-Hispanic Black</td>
<td></td>
<td style="text-align: left;">76%</td>
</tr>
<tr class="even">
<td></td>
<td>Non-Hispanic white</td>
<td></td>
<td style="text-align: left;">87%</td>
</tr>
<tr class="odd">
<td>Has place of routine care</td>
<td>Adults with insurance</td>
<td></td>
<td style="text-align: left;">86%</td>
</tr>
<tr class="even">
<td></td>
<td>Adults without insurance</td>
<td></td>
<td style="text-align: left;">57%</td>
</tr>
<tr class="odd">
<td><em>Cost-effectiveness analysis parameters</em></td>
<td></td>
<td></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td>State-specific quality-of-life weights</td>
<td>Healthy</td>
<td>1.0</td>
<td style="text-align: left;">1.0</td>
</tr>
<tr class="odd">
<td></td>
<td>Sick</td>
<td>0.7</td>
<td style="text-align: left;">0.7</td>
</tr>
<tr class="even">
<td>Annual state-specific costs</td>
<td>Healthy</td>
<td>$100</td>
<td style="text-align: left;">$100</td>
</tr>
<tr class="odd">
<td></td>
<td>Sick</td>
<td>$500</td>
<td style="text-align: left;">$500</td>
</tr>
<tr class="even">
<td>Annual treatment costs</td>
<td>Standard of care</td>
<td>$200</td>
<td style="text-align: left;">$200</td>
</tr>
<tr class="odd">
<td></td>
<td>New treatment</td>
<td>$6,000</td>
<td style="text-align: left;">$6,000</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="outcomes-and-analysis" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="outcomes-and-analysis"><span class="header-section-number">2.4</span> Outcomes and Analysis</h3>
<p>Our main analysis focused on health outcomes including life expectancy, cumulative incidence of sickness, years spent in the sick state, cumulative incidence of being diagnosed and treated, and years spent on treatment over the lifetime horizon. For all outcomes, we reported mean estimates and 95% confidence intervals based on the Monte Carlo standard errors (MCSEs) across the standard model and model incorporating our social factors framework.</p>
<p>As a secondary analysis, we conducted an illustrative cost-effectiveness analysis using both models in accordance with the Second Panel on Cost-Effectiveness in Health and Medicine.<span class="citation" data-cites="10.1093/acprof:oso/9780190492939.001.0001"><sup><a href="#ref-10.1093/acprof:oso/9780190492939.001.0001" role="doc-biblioref">2</a></sup></span> <a href="#tbl-table1" class="quarto-xref">Table&nbsp;1</a> shows parameters for the illustrative cost-effectiveness analysis. State-specific quality-of-life weights and costs differed by disease natural history states. Treatment costs for the standard of care and the new treatment accrued annually for individuals while they were on treatment. We computed mean and MCSE estimates of discounted quality-adjusted life years (QALYs), costs, and incremental cost-effectiveness ratios (ICERs), all discounted at 3% annually.</p>
</section>
</section>
<section id="results" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="results"><span class="header-section-number">3</span> Results</h2>
<p>Out of the 100,000 simulated individuals, 18% were non-Hispanic Black. In the model incorporating our social factors framework, non-Hispanic Black adults had lower rates of insurance coverage (77%) compared to non-Hispanic white adults (87%). Consequently, a smaller proportion of non-Hispanic Black adults started in the health system (80%) compared to non-Hispanic white adults (82%).</p>
<section id="health-outcomes" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="health-outcomes"><span class="header-section-number">3.1</span> Health outcomes</h3>
<section id="life-expectancy" class="level4" data-number="3.1.1">
<h4 data-number="3.1.1" class="anchored" data-anchor-id="life-expectancy"><span class="header-section-number">3.1.1</span> Life expectancy</h4>
<p>Under the standard model, non-Hispanic Black 40-year-old adults receiving the standard of care lived 28.9 years (95% CI: 28.7, 29.1) (<a href="#tbl-table2" class="quarto-xref">Table&nbsp;2</a>). Non-Hispanic white 40-year-old adults receiving the standard of care on average lived 3.9 years (95% CI: 3.7, 4.1) longer than non-Hispanic Black adults. With the new treatment, non-Hispanic Black and non-Hispanic white adults gained 2.7 years (95% CI: 2.6, 2.8) and 2.7 years (95% CI: 2.7, 2.8), respectively. The racial/ethnic disparity in life expectancy did not change.</p>
<p>Using the social factors framework, the racial/ethnic disparity in life expectancy under the standard of care was 0.3 years greater than the standard model at 4.2 years (95% CI: 4.0, 4.4), after accounting for differences in baseline health insurance coverage. In addition, life expectancy gains from the new treatment were smaller with the social factors framework compared to the standard model. Non-Hispanic Black adults and non-Hispanic white adults gained 0.7 fewer years at 2.0 years (95% CI: 1.9, 2.1) and 0.5 fewer years at 2.2 years (95% CI: 2.2, 2.3), respectively, compared to the standard model. With the social factors framework, adding the new treatment to the standard of care led to an increase in the racial/ethnic disparity in life expectancy between non-Hispanic Black and non-Hispanic white adults by 0.2 years to 4.4 years (95% CI: 4.2, 4.7).</p>
</section>
<section id="cumulative-incidence-of-sickness" class="level4" data-number="3.1.2">
<h4 data-number="3.1.2" class="anchored" data-anchor-id="cumulative-incidence-of-sickness"><span class="header-section-number">3.1.2</span> Cumulative incidence of sickness</h4>
<p>The lifetime cumulative incidence of sickness was 78% (95% CI: 77%, 78%) and 82% (95% CI: 82%, 83%) for non-Hispanic Black and non-Hispanic white adults, respectively, with the standard of care in the standard model. Because individuals with sickness cannot be cured, gains in number of years spent sick were years successfully managing and surviving the disease. When receiving the standard of care, non-Hispanic Black adults spent on average 16.8 years sick (95% CI: 16.7, 17.0), with an increase of 3.5 years (95% CI: 3.4, 3.6) when receiving the new treatment. Non-Hispanic white adults spent 19.9 years sick (95% CI: 19.8, 20.0) on average, with an increase of 3.3 years (95% CI: 3.3, 3.4) from the new treatment. The racial/ethnic difference in average years spent sick narrowed between non-Hispanic Black and non-Hispanic white adults from 3.1 years sick (95% CI: 2.9, 3.3) to 2.9 years sick (95% CI: 2.7, 3.2).</p>
<p>In the social factors framework, the lifetime cumulative incidence of sickness was 77% (95% CI: 77%, 78%) and 82% (95% CI: 82%, 82%) for non-Hispanic Black and non-Hispanic white adults, respectively. Compared to the standard model, the average gain in the number of years spent sick was lower for both groups: non-Hispanic Black adults gained 0.9 fewer years sick at 2.6 years (95% CI: 2.5, 2.7), and non-Hispanic white adults gained 0.6 fewer years sick at 2.7 years sick (95% CI: 2.7, 2.8). The racial/ethnic difference in the average number of years spent sick increased with the new treatment by 0.1 years to 3.5 years sick (95% CI: 3.3, 3.8).</p>
<div id="tbl-table2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-table2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Health outcomes results for standard model and social factors framework (Means [MCSEs])
</figcaption>
<div aria-describedby="tbl-table2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Group</th>
<th>Standard Model</th>
<th></th>
<th>Social Factors Framework</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td><em>Standard of Care</em></td>
<td><em>New Treatment</em></td>
<td><em>Standard of Care</em></td>
<td><em>New Treatment</em></td>
</tr>
<tr class="even">
<td>Life expectancy in years</td>
<td>Non-Hispanic Black</td>
<td>28.9 [0.1]</td>
<td>31.7 [0.1]</td>
<td>27.9 [0.1]</td>
<td>29.9 [0.1]</td>
</tr>
<tr class="odd">
<td></td>
<td>Non-Hispanic white</td>
<td>32.8 [&lt;0.1]</td>
<td>35.6 [&lt;0.1]</td>
<td>32.1 [&lt;0.1]</td>
<td>34.3 [&lt;0.1]</td>
</tr>
<tr class="even">
<td></td>
<td>Difference between groups</td>
<td>3.9 [0.1]</td>
<td>3.9 [0.1]</td>
<td>4.2 [0.1]</td>
<td>4.4 [0.1]</td>
</tr>
<tr class="odd">
<td>Cumulative incidence of sickness</td>
<td>Non-Hispanic Black</td>
<td>78% [&lt;1%]</td>
<td>78% [&lt;1%]</td>
<td>77% [&lt;1%]</td>
<td>77% [&lt;1%]</td>
</tr>
<tr class="even">
<td></td>
<td>Non-Hispanic white</td>
<td>82% [&lt;1%]</td>
<td>82% [&lt;1%]</td>
<td>82% [&lt;1%]</td>
<td>82% [&lt;1%]</td>
</tr>
<tr class="odd">
<td></td>
<td>Difference between groups</td>
<td>4% [&lt;1%]</td>
<td>4% [&lt;1%]</td>
<td>5% [&lt;1%]</td>
<td>5% [&lt;1%]</td>
</tr>
<tr class="even">
<td>Years spent with sickness</td>
<td>Non-Hispanic Black</td>
<td>16.8 [0.1]</td>
<td>20.4 [0.1]</td>
<td>15.7 [0.1]</td>
<td>18.3 [0.1]</td>
</tr>
<tr class="odd">
<td></td>
<td>Non-Hispanic white</td>
<td>19.9 [&lt;0.1]</td>
<td>23.3 [0.1]</td>
<td>19.1 [&lt;0.1]</td>
<td>21.8 [0.1]</td>
</tr>
<tr class="even">
<td></td>
<td>Difference between groups</td>
<td>3.1 [0.1]</td>
<td>2.9 [0.1]</td>
<td>3.4 [0.1]</td>
<td>3.5 [0.1]</td>
</tr>
<tr class="odd">
<td>Cumulative incidence of detected/treated</td>
<td>Non-Hispanic Black</td>
<td>63% [&lt;1%]</td>
<td>63% [&lt;1%]</td>
<td>51% [&lt;1%]</td>
<td>51% [&lt;1%]</td>
</tr>
<tr class="even">
<td></td>
<td>Non-Hispanic white</td>
<td>70% [&lt;1%]</td>
<td>70% [&lt;1%]</td>
<td>62% [&lt;1%]</td>
<td>62% [&lt;1%]</td>
</tr>
<tr class="odd">
<td></td>
<td>Difference between groups</td>
<td>7% [&lt;1%]</td>
<td>7% [&lt;1%]</td>
<td>11% [&lt;1%]</td>
<td>11% [&lt;1%]</td>
</tr>
<tr class="even">
<td>Years spent on treatment while sick</td>
<td>Non-Hispanic Black</td>
<td>10.9 [0.1]</td>
<td>14.1 [0.1]</td>
<td>8.4 [0.1]</td>
<td>10.7 [0.1]</td>
</tr>
<tr class="odd">
<td></td>
<td>Non-Hispanic white</td>
<td>13.1 [&lt;0.1]</td>
<td>16.1 [0.1]</td>
<td>11.0 [&lt;0.1]</td>
<td>13.4 [0.1]</td>
</tr>
<tr class="even">
<td></td>
<td>Difference between groups</td>
<td>2.1 [0.1]</td>
<td>1.9 [0.1]</td>
<td>2.6 [0.1]</td>
<td>2.7 [0.1]</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-healthsystem" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="sec-healthsystem"><span class="header-section-number">3.2</span> Health system utilization</h3>
<p>All individuals started in the health system with regular healthcare and were eligible for detection and treatment for sickness in the standard model. The cumulative lifetime incidence of being detected and treated when receiving the new treatment was 69% (95% CI: 69%, 69%) across the cohort, with 63% (95% CI: 62%, 64%) and 70% (95% CI: 70%, 71%) for non-Hispanic Black and non-Hispanic white adults, respectively. When receiving the new treatment, non-Hispanic Black adults and non-Hispanic white adults spent 14.1 years sick (95% CI: 13.9, 14.3) and 16.1 years sick (95% CI: 16.0, 16.2) on treatment. Adults from both racial/ethnic groups spent on average 69% of their sick years on the new treatment.</p>
<p>For the social factors framework, 18% of individuals started out of the health system. Therefore, the cumulative lifetime incidence of being detected and treated was lower than the standard model by 9% at 60% (95% CI: 59%, 60%) (<a href="#fig-health-utilization-1" class="quarto-xref">Figure&nbsp;3 (a)</a>). Incidence of being detected and treated was 12% and 9% lower compared to the standard model for non-Hispanic Black and non-Hispanic white adults, respectively. These differences were driven by differences in health insurance coverage, which influenced transitions into the health system and access to treatment. Individuals with insurance had a higher cumulative incidence of being detected and treated at 66% (95% CI: 66%, 67%) throughout their lifetime, thus benefiting from the new treatment, compared to individuals without insurance at 22% (95% CI: 21%, 22%) (<a href="#fig-health-utilization-2" class="quarto-xref">Figure&nbsp;3 (b)</a>).</p>
<p>Additionally, non-Hispanic Black adults and non-Hispanic white adults spent a lower percentage of their sick years on the new treatment in the social factors framework implementation compared to the standard model. Non-Hispanic Black and non-Hispanic white adults spent 10.7 years (95% CI: 10.5, 10.9) and 13.4 years (95% CI: 13.3, 13.5) on treatment, or 59% and 61% of their years sick, respectively. After accounting for heterogeneity in health insurance coverage with the social factors framework, non-Hispanic white patients spent a greater proportion of sick years on the new treatment (3 percentage points) compared to non-Hispanic Black adults.</p>
<div class="cell" data-layout-nrow="2" data-execution_count="7">
<div id="fig-health-utilization" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-health-utilization-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-health-utilization" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-health-utilization-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-health-utilization-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_draft_files/figure-html/fig-health-utilization-output-1.png" data-ref-parent="fig-health-utilization" width="833" height="600" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-health-utilization-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Comparison between standard model and social factors framework
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-health-utilization" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-health-utilization-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-health-utilization-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_draft_files/figure-html/fig-health-utilization-output-2.png" data-ref-parent="fig-health-utilization" width="833" height="593" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-health-utilization-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Comparison between individuals with and without health insurance in social factors framework
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-health-utilization-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Prevalence of health system utilization states
</figcaption>
</figure>
</div>
</div>
</section>
<section id="cost-effectiveness-analysis" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="cost-effectiveness-analysis"><span class="header-section-number">3.3</span> Cost-effectiveness analysis</h3>
<p>Lastly, we summarize differences in our cost-effectiveness analyses. Discounted expected lifetime healthcare costs when receiving the standard of care in the standard model were $5,800 (95% CI: $5,800, $5,900) for a 40-year-old non-Hispanic Black adult (<a href="#supptbl-cost-qaly" class="quarto-xref">Table S1</a>). Adding the new treatment, which cost $6,000 per year, increased expected lifetime healthcare costs by $31,400 (95% CI: $30,800, $31,900). The new treatment yielded QALY gains of 0.7 (95% CI: 0.7, 0.7) compared to standard of care. For non-Hispanic white adults, discounted expected lifetime costs when receiving the standard of care were $6,800 (95% CI: $6,800, $6,800). Adding the new treatment increased discounted lifetime healthcare costs by $36,400 (95% CI: $36,200, $36,700) and QALYs by 0.6 (95% CI: 0.6, 0.6). The ICER for adding the new treatment was higher for non-Hispanic white adults ($57,100 per QALY gained) compared to non-Hispanic Black adults ($46,200 per QALY gained) (<a href="#supptbl-NHW-CEA" class="quarto-xref">Table S2</a>, <a href="#supptbl-NHB-CEA" class="quarto-xref">Table S3</a>).</p>
<p>The new treatment resulted in lower QALY gains and healthcare cost increases in the social factors framework due to reduced access to treatment, as observed in <a href="#sec-healthsystem" class="quarto-xref">Section&nbsp;3.2</a>. These changes were more pronounced for non-Hispanic Black adults, who had lower health insurance coverage compared to non-Hispanic white adults (<a href="#fig-cost-effectiveness" class="quarto-xref">Figure&nbsp;4</a>). For non-Hispanic Black adults, lifetime healthcare costs increased by $23,600 (95% CI: $23,100, $24,100) with the new treatment, on average $7,700 (95% CI: $7,000, $8,500) less than computed in the standard model. QALY gains using the social factors framework were also 0.2 smaller (95% CI: 0.1, 0.2) at 0.5 (95% CI: 0.5, 0.5). For non-Hispanic white adults, the new treatment increased lifetime healthcare costs and QALYs by $30,300 (95% CI: $30,000, $30,500) and 0.5 (95% CI: 0.5, 0.5), respectively, $6,200 fewer dollars spent (95% CI: $5,800, $6,500) and 0.1 fewer QALYs (95% CI: 0.1, 0.1) than in the standard model.</p>
<p>The ICERs for adding the new treatment were less favorable when using the social factors framework compared to the standard model. Adding the new treatment cost $46,900 and $57,600 per QALY gained for non-Hispanic Black and non-Hispanic white adults, respectively, on average $700 and $500 higher than in the standard model. ICERs for adding the new treatment were consistently lower for non-Hispanic Black adults compared to non-Hispanic white adults across both models.</p>
<div class="cell" data-layout-nrow="2" data-execution_count="9">
<div id="fig-cost-effectiveness" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cost-effectiveness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cost-effectiveness" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-cost-effectiveness-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cost-effectiveness-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_draft_files/figure-html/fig-cost-effectiveness-output-1.png" data-ref-parent="fig-cost-effectiveness" width="933" height="647" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cost-effectiveness-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Non-Hispanic Black adults
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cost-effectiveness" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-cost-effectiveness-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cost-effectiveness-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="manuscript_draft_files/figure-html/fig-cost-effectiveness-output-2.png" data-ref-parent="fig-cost-effectiveness" width="846" height="593" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cost-effectiveness-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Non-Hispanic white adults
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cost-effectiveness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Cost-effectiveness planes
</figcaption>
</figure>
</div>
</div>
</section>
</section>
<section id="discussion" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="discussion"><span class="header-section-number">4</span> Discussion</h2>
<p>Our findings underscore the importance of incorporating social factors in health policy simulation models. In the simplified decision problem, we found that failing to consider social factors produced biased estimates of benefits, healthcare utilization, costs, and health disparities. Results from the standard model suggested that the new treatment would have no impact on health disparities between non-Hispanic Black and non-Hispanic white adults. However, with our social factors framework, the opposite was observed: non-Hispanic white adults experienced greater health outcome gains from the new treatment, which exacerbated health disparities between the two racial/ethnic groups.</p>
<p>These differences can be attributed to including a key social factor, health insurance coverage. In the social factors framework, we assumed that health insurance status impacted both baseline mortality rates and access to regular healthcare. This first assumption reflected evidence from prior studies that uninsured individuals may face higher baseline mortality risks due to increased prevalence of underlying health conditions, inadequate access to healthcare for other conditions, and increased stress.<span class="citation" data-cites="wilper2009health kronick2009health"><sup><a href="#ref-wilper2009health" role="doc-biblioref">6</a>,<a href="#ref-kronick2009health" role="doc-biblioref">11</a></sup></span> The second assumption asserted that insurance status influenced disease-specific outcomes by affecting healthcare and treatment access.<span class="citation" data-cites="fernandez2019medication tolbert2024uninsured"><sup><a href="#ref-fernandez2019medication" role="doc-biblioref">8</a>,<a href="#ref-tolbert2024uninsured" role="doc-biblioref">9</a></sup></span> Due to racial/ethnic differences in health insurance coverage, with the social factors framework, non-Hispanic Black adults spent a smaller proportion of their sick years receiving treatment compared to non-Hispanic white adults. Reduced treatment access diminished the potential benefits of implementing the new treatment for the non-Hispanic Black group. Our social factors framework highlighted inequities in treatment access and the downstream effect on health outcomes, which was overlooked in the standard model.</p>
<p>The cost-effectiveness analysis further emphasized these results. Adding the new treatment to standard of care yielded smaller QALY gains in the social factors framework compared to the standard model for both racial/ethnic groups, with reductions being more pronounced for non-Hispanic Black adults. Despite these diminished QALY gains, ICERs remained largely consistent between the two models. Reduced access to treatment lowered both incremental QALYs and costs and kept ICERs relatively consistent. It is possible that ICERs may diverge by including the social factors framework in other scenarios involving high up-front costs for diagnosis and treatment initiation, attenuated treatment effectiveness over time, or changes in quality-of-life weights that vary with different health system states. Results from the simplified decision problem highlight two limitations of traditional cost-effectiveness analyses in addressing health disparities. First, as demonstrated by the standard model, these methods often assume homogeneous and guaranteed access to healthcare within the target population. When we accounted for real-world heterogeneity in healthcare access using the social factors framework, the projected incremental costs and QALYs changed. Second, conventional cost-effectiveness metrics do not capture distributional effects on costs and health outcomes, as ICERs cannot reflect for whom benefits were the largest. These findings reinforce that traditional cost-effectiveness analyses alone may be insufficient to inform decision-making on interventions with health equity implications.</p>
<p>Health policy simulation models have faced criticism for their lack of effectiveness in addressing health disparities.<span class="citation" data-cites="basu2024risk"><sup><a href="#ref-basu2024risk" role="doc-biblioref">12</a></sup></span> The Second Panel on Cost-effectiveness and Medicine discussed the importance of assessing who within a population benefits from health interventions, often referred to as the distributional impact.<span class="citation" data-cites="10.1093/acprof:oso/9780190492939.003.0012"><sup><a href="#ref-10.1093/acprof:oso/9780190492939.003.0012" role="doc-biblioref">13</a></sup></span> To fill this gap, several approaches have been developed, including equity impact analyses, extended cost-effectiveness analyses, and distributional cost-effectiveness analyses.<span class="citation" data-cites="asaria2016distributional verguet2016extended pitt2020public avancena2021examining"><sup><a href="#ref-asaria2016distributional" role="doc-biblioref">14</a>–<a href="#ref-avancena2021examining" role="doc-biblioref">17</a></sup></span> However, these methods do not include recommendations for how to explicitly model social factors and their relationship to disease progression or health system utilization. In particular, distributional cost-effectiveness analyses offer a framework for navigating equity-efficiency trade-offs in decision-making. While the social factors framework does not address these trade-offs, it can improve estimates of the distribution of costs and benefits accrued to individuals across dimensions of disparities required in extended and distributional cost-effectiveness analyses. Additionally, other research has considered including social determinants of health in health policy modeling,<span class="citation" data-cites="ali2024incorporating"><sup><a href="#ref-ali2024incorporating" role="doc-biblioref">18</a></sup></span> but to our knowledge, no formal framework exists for integrating these factors into health policy simulation models.</p>
<p>Our social factors framework has several limitations. First, the limited availability and quality of individual-level data on social drivers of health can be a nontrivial challenge.<span class="citation" data-cites="chunara2024social"><sup><a href="#ref-chunara2024social" role="doc-biblioref">19</a></sup></span> These data are often incomplete, requiring researchers to rely on location-based proxies, such as administrative or geographic units (e.g., census tract, postal codes, regional divisions).<span class="citation" data-cites="cottrell2020comparison"><sup><a href="#ref-cottrell2020comparison" role="doc-biblioref">20</a></sup></span> Building models to address health equity concerns will benefit from greater investment in high-quality, individual-level data on social factors.<span class="citation" data-cites="clark2017integrating gottlieb2013collecting"><sup><a href="#ref-clark2017integrating" role="doc-biblioref">21</a>,<a href="#ref-gottlieb2013collecting" role="doc-biblioref">22</a></sup></span> Second, incorporating social factors into health policy simulation models requires careful consideration of their complex causal pathways.<span class="citation" data-cites="braveman2014social rehkopf2016consistency kaufman1999seeking"><sup><a href="#ref-braveman2014social" role="doc-biblioref">23</a>–<a href="#ref-kaufman1999seeking" role="doc-biblioref">25</a></sup></span> Third, it may be necessary to consider heterogeneity in treatment effectiveness or disease-specific mortality risks, which may vary directly or indirectly due to social drivers of health, family history, or genetic factors. Finally, it may be challenging to apply in certain types of health policy simulation models. For example, state-transition cohort models are generally used for simulating homogeneous cohorts, therefore, incorporating our framework to account for heterogeneous social factors would require stratification.</p>
<p>In our simplified decision problem, we demonstrated that ignoring heterogeneous health insurance coverage led to the incorrect conclusion that the new treatment did not exacerbate health disparities, potentially resulting in misinformed policy recommendations. By incorporating social factors, our framework permits the evaluation of an intervention’s social impact before implementation and facilitates comparisons between clinical and social interventions. Our approach enhances the utility of decision-analytic models as a more effective tool for evaluating health interventions with equity considerations.</p>
</section>










<div id="quarto-appendix" class="default"><section id="acknowledgments" class="level2 appendix unnumbered"><h2 class="anchored quarto-appendix-heading">Acknowledgments</h2><div class="quarto-appendix-contents">

<p>We thank Malcolm Barrett for his valuable contributions in code review and the Health Policy Data Science Lab for feedback on figure design.</p>
</div></section><section id="ethical-considerations" class="level2 appendix unnumbered"><h2 class="anchored quarto-appendix-heading">Ethical considerations</h2><div class="quarto-appendix-contents">

<p>This study did not require Institutional Review Board approval because all data were publicly available and did not involve human participants.</p>
</div></section><section id="consent-to-participate" class="level2 appendix unnumbered"><h2 class="anchored quarto-appendix-heading">Consent to participate</h2><div class="quarto-appendix-contents">

<p>Not applicable</p>
</div></section><section id="patient-consent" class="level2 appendix unnumbered"><h2 class="anchored quarto-appendix-heading">Patient consent</h2><div class="quarto-appendix-contents">

<p>Not applicable</p>
</div></section><section id="consent-to-publish" class="level2 appendix unnumbered"><h2 class="anchored quarto-appendix-heading">Consent to publish</h2><div class="quarto-appendix-contents">

<p>Not applicable</p>
</div></section><section id="conflicts-of-interest" class="level2 appendix unnumbered"><h2 class="anchored quarto-appendix-heading">Conflicts of interest</h2><div class="quarto-appendix-contents">

<p>The Authors declare no potential conflicts of interest with respect to the research, authorship, and/or publication of this article.</p>
</div></section><section id="funding-statement" class="level2 appendix unnumbered"><h2 class="anchored quarto-appendix-heading">Funding statement</h2><div class="quarto-appendix-contents">

<p>Financial support for this study was provided by the National Institutes of Health and a Stanford Interdisciplinary Graduate Fellowship. Marika Cusick, Fernando Alarid-Escudero, Jeremy D. Goldhaber-Fiebert and Sherri Rose were supported by NIH Director’s Pioneer Award DP1LM014278. Marika Cusick was additionally supported by the Stanford Interdisciplinary Graduate Fellowship. The funding agencies had no role in the design of the study, interpretation of results, or writing of the manuscript. The funding agreement ensured the authors’ independence in designing the study, interpreting the data, writing, and publishing the report.</p>
</div></section><section id="data-availability" class="level2 appendix unnumbered"><h2 class="anchored quarto-appendix-heading">Data availability</h2><div class="quarto-appendix-contents">

<p>The Python code to reproduce our results are available at: <a href="https://github.com/StanfordHPDS/social_factors_microsim" class="uri">https://github.com/StanfordHPDS/social_factors_microsim</a>.</p>
</div></section><section id="supplement-tables" class="level2 appendix unnumbered"><h2 class="anchored quarto-appendix-heading">Supplement Tables</h2><div class="quarto-appendix-contents">

<div id="supptbl-cost-qaly" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-supptbl figure">
<div aria-describedby="supptbl-cost-qaly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Group</th>
<th>Standard Model</th>
<th></th>
<th>Social Factors Framework</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td><em>Standard of Care</em></td>
<td><em>New Treatment</em></td>
<td><em>Standard of Care</em></td>
<td><em>New Treatment</em></td>
</tr>
<tr class="even">
<td>QALYs</td>
<td>Non-Hispanic Black</td>
<td>16.5 [&lt;0.1]</td>
<td>17.2 [&lt;0.1]</td>
<td>16.2 [&lt;0.1]</td>
<td>16.7 [&lt;0.1]</td>
</tr>
<tr class="odd">
<td></td>
<td>Non-Hispanic white</td>
<td>17.8 [&lt;0.1]</td>
<td>18.5 [&lt;0.1]</td>
<td>17.6 [&lt;0.1]</td>
<td>18.1 [&lt;0.1]</td>
</tr>
<tr class="even">
<td></td>
<td>Difference between groups</td>
<td>1.3 [&lt;0.1]</td>
<td>1.2 [&lt;0.1]</td>
<td>1.4 [&lt;0.1]</td>
<td>1.4 [&lt;0.1]</td>
</tr>
<tr class="odd">
<td>Costs</td>
<td>Non-Hispanic Black</td>
<td>$5,800 [&lt;$100]</td>
<td>$37,200 [$300]</td>
<td>$5,400 [&lt;$100]</td>
<td>$29,000 [$300]</td>
</tr>
<tr class="even">
<td></td>
<td>Non-Hispanic white</td>
<td>$6,800 [&lt;$100]</td>
<td>$43,200 [$100]</td>
<td>$6,400 [&lt;$100]</td>
<td>$36,700 [$100]</td>
</tr>
<tr class="odd">
<td></td>
<td>Difference between groups</td>
<td>$1,000 [&lt;$100]</td>
<td>$6,000 [$300]</td>
<td>$1,100 [&lt;$100]</td>
<td>$7,700 [$300]</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-supptbl" id="supptbl-cost-qaly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table S1: Cost and QALY outcomes for non-Hispanic Black and non-Hispanic white adults
</figcaption>
</figure>
</div>
<div id="supptbl-NHW-CEA" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-supptbl figure">
<div aria-describedby="supptbl-NHW-CEA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Framework</th>
<th>Strategy</th>
<th>Cost</th>
<th>QALY</th>
<th>Incremental Cost</th>
<th>Incremental QALY</th>
<th>Incremental Cost-Effectiveness Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Standard model</td>
<td>Standard of care</td>
<td>$6,800</td>
<td>17.8</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>New treatment</td>
<td>$43,200</td>
<td>18.5</td>
<td>$36,400</td>
<td>0.6</td>
<td>$57,100</td>
</tr>
<tr class="odd">
<td>Social factors framework</td>
<td>Standard of care</td>
<td>$6,400</td>
<td>17.6</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>New treatment</td>
<td>$36,700</td>
<td>18.1</td>
<td>$30,300</td>
<td>0.5</td>
<td>$57,600</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-supptbl" id="supptbl-NHW-CEA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table S2: Cost-effectiveness results for non-Hispanic white adults
</figcaption>
</figure>
</div>
<div id="supptbl-NHB-CEA" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-supptbl figure">
<div aria-describedby="supptbl-NHB-CEA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Framework</th>
<th>Strategy</th>
<th>Cost</th>
<th>QALY</th>
<th>Incremental Cost</th>
<th>Incremental QALY</th>
<th>Incremental Cost-Effectiveness Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Standard model</td>
<td>Standard of care</td>
<td>$37,200</td>
<td>16.5</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>New treatment</td>
<td>$37,200</td>
<td>17.2</td>
<td>$31,400</td>
<td>0.7</td>
<td>$46,200</td>
</tr>
<tr class="odd">
<td>Social factors framework</td>
<td>Standard of care</td>
<td>$5,400</td>
<td>16.2</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>New treatment</td>
<td>$29,000</td>
<td>16.7</td>
<td>$23,600</td>
<td>0.5</td>
<td>$46,900</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-supptbl" id="supptbl-NHB-CEA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table S3: Cost-effectiveness results for non-Hispanic Black adults
</figcaption>
</figure>
</div>

</div></section><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body" role="list">
<div id="ref-sanders2016recommendations" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Sanders GD, Neumann PJ, Basu A, et al. Recommendations for conduct, methodological practices, and reporting of cost-effectiveness analyses: Second panel on cost-effectiveness in health and medicine. <em>Jama</em> 2016; 316: 1093–1103.</div>
</div>
<div id="ref-10.1093/acprof:oso/9780190492939.001.0001" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Neumann PJ, Ganiats TG, Russell LB, et al. <em><span class="nocase">Cost-Effectiveness in Health and Medicine</span></em>. Oxford University Press. Epub ahead of print December 2016. DOI: <a href="https://doi.org/10.1093/acprof:oso/9780190492939.001.0001">10.1093/acprof:oso/9780190492939.001.0001</a>.</div>
</div>
<div id="ref-hood2016county" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Hood CM, Gennuso KP, Swain GR, et al. County health rankings: Relationships between determinant factors and health outcomes. <em>American journal of preventive medicine</em> 2016; 50: 129–135.</div>
</div>
<div id="ref-krijkamp2018microsimulation" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Krijkamp EM, Alarid-Escudero F, Enns EA, et al. Microsimulation modeling for health decision sciences using r: A tutorial. <em>Medical Decision Making</em> 2018; 38: 400–422.</div>
</div>
<div id="ref-arias2023united" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Arias E, Xu J, Kochanek K. United states life tables, 2021.</div>
</div>
<div id="ref-wilper2009health" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Wilper AP, Woolhandler S, Lasser KE, et al. Health insurance and mortality in US adults. <em>American journal of public health</em> 2009; 99: 2289–2295.</div>
</div>
<div id="ref-hill2024health" class="csl-entry" role="listitem">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Hill L, Artiga S, Damico A. Health coverage by race and ethnicity, 2010-2022, <a href="https://www.kff.org/racial-equity-and-health-policy/issue-brief/health-coverage-by-race-and-ethnicity/">https://www.kff.org/racial-equity-and-health-policy/issue-brief/health-coverage-by-race-and-ethnicity/</a> (2024).</div>
</div>
<div id="ref-fernandez2019medication" class="csl-entry" role="listitem">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Fernandez-Lazaro CI, Adams DP, Fernandez-Lazaro D, et al. Medication adherence and barriers among low-income, uninsured patients with multiple chronic conditions. <em>Research in Social and Administrative Pharmacy</em> 2019; 15: 744–753.</div>
</div>
<div id="ref-tolbert2024uninsured" class="csl-entry" role="listitem">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Tolbert J, Drake P, Singh R. The uninsured population and health coverage. In: Altman D (ed) <em>Health policy 101</em>. KFF,<a href=" https://www.kff.org/health-policy-101-the-uninsured-population-and-health-coverage/"> https://www.kff.org/health-policy-101-the-uninsured-population-and-health-coverage/</a> (2024).</div>
</div>
<div id="ref-CDC2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Health USD of, Human Services C for DC, Prevention. National health and nutrition examination survey data.</div>
</div>
<div id="ref-kronick2009health" class="csl-entry" role="listitem">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Kronick R. Health insurance coverage and mortality revisited. <em>Health services research</em> 2009; 44: 1211–1231.</div>
</div>
<div id="ref-basu2024risk" class="csl-entry" role="listitem">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">Basu S, Venkataramani AS, Schillinger D. The risk of perpetuating health disparities through cost-effectiveness analyses: Article examines the risk of perpetuating health disparities through cost-effectiveness assessments. <em>Health Affairs</em> 2024; 43: 1165–1171.</div>
</div>
<div id="ref-10.1093/acprof:oso/9780190492939.003.0012" class="csl-entry" role="listitem">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Brock DW, Daniels N, Neumann PJ, et al. <span class="nocase">319Ethical and Distributive Considerations</span>. In: <em><span class="nocase">Cost-Effectiveness in Health and Medicine</span></em>. Oxford University Press. Epub ahead of print December 2016. DOI: <a href="https://doi.org/10.1093/acprof:oso/9780190492939.003.0012">10.1093/acprof:oso/9780190492939.003.0012</a>.</div>
</div>
<div id="ref-asaria2016distributional" class="csl-entry" role="listitem">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Asaria M, Griffin S, Cookson R. Distributional cost-effectiveness analysis: A tutorial. <em>Medical Decision Making</em> 2016; 36: 8–19.</div>
</div>
<div id="ref-verguet2016extended" class="csl-entry" role="listitem">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Verguet S, Kim JJ, Jamison DT. Extended cost-effectiveness analysis for health policy assessment: A tutorial. <em>Pharmacoeconomics</em> 2016; 34: 913–923.</div>
</div>
<div id="ref-pitt2020public" class="csl-entry" role="listitem">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Pitt AL, Goldhaber-Fiebert JD, Brandeau ML. Public health interventions with harms and benefits: A graphical framework for evaluating tradeoffs. <em>Medical Decision Making</em> 2020; 40: 978–989.</div>
</div>
<div id="ref-avancena2021examining" class="csl-entry" role="listitem">
<div class="csl-left-margin">17. </div><div class="csl-right-inline">Avanceña AL, Prosser LA. Examining equity effects of health interventions in cost-effectiveness analysis: A systematic review. <em>Value in Health</em> 2021; 24: 136–143.</div>
</div>
<div id="ref-ali2024incorporating" class="csl-entry" role="listitem">
<div class="csl-left-margin">18. </div><div class="csl-right-inline">Ali S, Li Z, Moqueet N, et al. Incorporating social determinants of health in infectious disease models: A systematic review of guidelines. <em>Medical Decision Making</em> 2024; 0272989X241280611.</div>
</div>
<div id="ref-chunara2024social" class="csl-entry" role="listitem">
<div class="csl-left-margin">19. </div><div class="csl-right-inline">Chunara R, Gjonaj J, Immaculate E, et al. Social determinants of health: The need for data science methods and capacity. <em>The Lancet Digital Health</em> 2024; 6: e235–e237.</div>
</div>
<div id="ref-cottrell2020comparison" class="csl-entry" role="listitem">
<div class="csl-left-margin">20. </div><div class="csl-right-inline">Cottrell EK, Hendricks M, Dambrun K, et al. Comparison of community-level and patient-level social risk data in a network of community health centers. <em>JAMA network open</em> 2020; 3: e2016852–e2016852.</div>
</div>
<div id="ref-clark2017integrating" class="csl-entry" role="listitem">
<div class="csl-left-margin">21. </div><div class="csl-right-inline">Clark MA, Gurewich D. Integrating measures of social determinants of health into health care encounters: Opportunities and challenges. <em>Medical Care</em> 2017; 55: 807–809.</div>
</div>
<div id="ref-gottlieb2013collecting" class="csl-entry" role="listitem">
<div class="csl-left-margin">22. </div><div class="csl-right-inline">Gottlieb L, Sandel M, Adler NE. Collecting and applying data on social determinants of health in health care settings. <em>JAMA internal medicine</em> 2013; 173: 1017–1020.</div>
</div>
<div id="ref-braveman2014social" class="csl-entry" role="listitem">
<div class="csl-left-margin">23. </div><div class="csl-right-inline">Braveman P, Gottlieb L. The social determinants of health: It’s time to consider the causes of the causes. <em>Public health reports</em> 2014; 129: 19–31.</div>
</div>
<div id="ref-rehkopf2016consistency" class="csl-entry" role="listitem">
<div class="csl-left-margin">24. </div><div class="csl-right-inline">Rehkopf DH, Glymour MM, Osypuk TL. The consistency assumption for causal inference in social epidemiology: When a rose is not a rose. <em>Current epidemiology reports</em> 2016; 3: 63–71.</div>
</div>
<div id="ref-kaufman1999seeking" class="csl-entry" role="listitem">
<div class="csl-left-margin">25. </div><div class="csl-right-inline">Kaufman JS, Cooper RS. Seeking causal explanations in social epidemiology. <em>American journal of epidemiology</em> 1999; 150: 113–120.</div>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>